DATASET_NAME = 'DeepFashion'
EMBEDDING_TYPE = 'roberta'
CONFIG_NAME = ''
GPU_ID = '0'
CUDA = True
WORKERS = 6

NET_G = ''
NET_D = ''
STAGE1_G = './output/DeepFashion__2025_03_14_13_30_38/Model/netG_epoch_100.pth'

DATA_DIR = ''
VAL_DIR = ''

VIS_COUNT = 64

Z_DIM = 100
IMSIZE = 64
STAGE = 2

TRAIN_FLAG = True
TRAIN_BATCH_SIZE = 64
TRAIN_MAX_EPOCH = 100
TRAIN_SNAPSHOT_INTERVAL = 5
TRAIN_PRETRAINED_MODEL = ''
TRAIN_PRETRAINED_EPOCH = 600
TRAIN_LR_DECAY_EPOCH = 20
TRAIN_DISCRIMINATOR_LR = 0.0002
TRAIN_GENERATOR_LR = 0.0002

TRAIN_COEFF_KL = 2.0

GAN_CONDITION_DIM = 128
GAN_DF_DIM = 96
GAN_GF_DIM = 192
GAN_R_NUM = 2

TEXT_DIMENSION = 1024

EMBEDDING_FILENAME = "/char-CNN-RNN-embeddings.pickle"
